{{- if .Values.a2aserver.enabled }}
apiVersion: ark.mckinsey.com/v1prealpha1
kind: A2AServer
metadata:
  name: {{ .Values.a2aserver.name }}
  {{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  address:
    valueFrom:
      serviceRef:
        name: {{ .Values.service.name }}
        port: http
  description: "Go Task-Based A2A Agent that returns task structures for debugging protocol issues"
{{- end }}