version: 2
registries:
  tfe:
    type: terraform-registry
    url: https://terraform.mckinsey.cloud
    token: ${{ secrets.TF_API_TOKEN }}
  git:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.GA_PAT }}

updates:
  - package-ecosystem: github-actions
    directory: '.github/workflows'
    commit-message:
      prefix: 'chore: '
    schedule:
      interval: weekly
    registries:
      - "git"
  - package-ecosystem: "terraform"
    directories:
      - "infrastructure/*/*/*"
    commit-message:
      prefix: 'chore: '
    schedule:
      interval: weekly
    registries:
     - "tfe"