# DevSpace configuration for local ARK services development
version: v2beta1

# Hooks for pre-build setup
hooks:
  - command: bash -c "make ark-sdk-build && mkdir -p services/ark-api/ark-api/wheels && cp out/ark-sdk/py-sdk/dist/ark_sdk-*.whl services/ark-api/ark-api/wheels/"
    events: ["before:build:ark-api"]

# Deployment pipelines define the workflow for different commands
pipelines:
  # 'devspace deploy' - Build and deploy without development features
  deploy: |-
    build_images --all
    create_deployments --all

  # 'devspace dev' - Full development workflow with hot reload
  dev: |-
    build_images --all
    create_deployments --all
    start_dev --all

# Image build configuration
images:
  # ARK API service
  ark-api:
    image: ark-api
    dockerfile: ./services/ark-api/Dockerfile
    context: ./services/ark-api
    target: dev

  # ARK Dashboard service
  ark-dashboard:
    image: ark-dashboard
    dockerfile: ./services/ark-dashboard/Dockerfile
    context: ./services/ark-dashboard
    target: dev

# Kubernetes deployments
deployments:
  ark-api:
    namespace: default
    helm:
      chart:
        path: ./services/ark-api/chart
      values:
        app:
          image:
            repository: ${runtime.images.ark-api.image}
            tag: ${runtime.images.ark-api.tag}
          # Override resources for in-cluster local development - API with live reload needs more memory and CPU than production
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "200m"

  ark-dashboard:
    namespace: default
    helm:
      chart:
        path: ./services/ark-dashboard/chart
      values:
        app:
          image:
            repository: ${runtime.images.ark-dashboard.image}
            tag: ${runtime.images.ark-dashboard.tag}
          # Override resources for in-cluster local development - Next.js + Turbopack compilation needs 3GB+ memory and 2 CPU cores for fast builds
          resources:
            limits:
              memory: "3072Mi"
              cpu: "2000m"
            requests:
              memory: "256Mi"
              cpu: "200m"

# Development configuration - active during 'devspace dev'
dev:
  ark-api:
    imageSelector: ark-api
    namespace: default
    # Uncomment to forward ports to local host
    # ports:
    #   - port: 8000:8000  # FastAPI server
    # Stream logs instead of terminal
    logs:
      lastLines: 50
    # File synchronization for hot reload
    sync:
      - path: ./services/ark-api/ark-api:/app
        excludePaths:
          # Exclude dependency files - pyproject.toml is patched at build time with wheel dependencies
          # This is a temporary workaround until we publish our package to PyPI
          - pyproject.toml
          - uv.lock
          # Don't synchronise virtual environment
          - .venv
    # Enable SSH for IDE integration
    ssh:
      enabled: true

  ark-dashboard:
    imageSelector: ark-dashboard
    namespace: default
    # Uncomment to forward ports to local host
    # ports:
    #   - port: 3000:3000  # Next.js dev server
    # Stream logs instead of terminal
    logs:
      lastLines: 50
    # File synchronization for hot reload
    sync:
      - path: ./services/ark-dashboard/ark-dashboard:/app
        excludePaths:
          - node_modules/
          - .next/
          - .git/
          - "*.log"
    # Enable SSH for IDE integration
    ssh:
      enabled: true