name: Generate kubeconfig with GitHub OIDC
description: |
  Generates a kubeconfig file with the GitHub OIDC provider.

  This action will generate a kubeconfig that uses the GitHub OIDC provider
  to authenticate with the Kubernetes cluster. The kubeconfig will be stored
  in the default kubeconfig path: ~/.kube/config. Validity of the kubeconfig
  is 5 minutes.

inputs:
  cluster_login_url:
    description: 'The URL of the Kubernetes cluster'
    type: string
    required: true
  idp_issuer_url:
    description: 'The OIDC issuer URL for authentication'
    type: string
    required: true
  kubectl_version:
    description: 'The version of kubectl to use'
    type: string
    required: false
    default: 'v1.28.0'

runs:
  using: composite

  steps:
    - uses: azure/setup-kubectl@v4
      id: install
      with:
        version: ${{ inputs.kubectl_version }}

    - name: Install OIDC Client from Core Package
      shell: bash
      run: npm install @actions/core@1.6.0 @actions/http-client

    - name: Get Id Token
      uses: actions/github-script@v7
      with:
        script: |
          let id_token = await core.getIDToken()
          core.exportVariable("ID_TOKEN", id_token);

    - name: Generate kubeconfig using Github OIDC
      env:
        CLUSTER_URL: ${{ inputs.cluster_login_url }}
        KUBECONFIG_USER_TOKEN: ${{ env.ID_TOKEN }}
        IDP_ISSUER_URL: ${{ inputs.idp_issuer_url }}
      shell: bash
      run: ${{github.action_path}}/get-kubeconfig.sh
