name: 'Collect Coverage'
description: 'Collects coverage data from specified path and uploads as artifacts'

inputs:
  source-path:
    description: 'Path where coverage files are located'
    required: true
  artifact-folder:
    description: 'Folder name in coverage/ to store the artifacts'
    required: true
  artifact-suffix:
    description: 'Suffix for the artifact name to make it unique'
    required: true

runs:
  using: composite
  steps:
    - name: Collect coverage data
      shell: bash
      run: |
        echo "Collecting coverage data from ${{ inputs.source-path }}"
        
        # Create output directory
        mkdir -p coverage/${{ inputs.artifact-folder }}
        
        # Copy coverage files from source path
        if [ -f "${{ inputs.source-path }}" ]; then
          # Single file
          cp ${{ inputs.source-path }} coverage/${{ inputs.artifact-folder }}/
        elif [ -d "${{ inputs.source-path }}" ]; then
          # Directory (include hidden files)
          cp -r ${{ inputs.source-path }}/. coverage/${{ inputs.artifact-folder }}/
        else
          echo "Source path not found: ${{ inputs.source-path }}"
          exit 1
        fi
        echo "Coverage files copied to coverage/${{ inputs.artifact-folder }}/"

    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage-${{ inputs.artifact-suffix }}
        path: coverage/
        retention-days: 30