apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: evaluator-access-default
rules:
- apiGroups: ["ark.mckinsey.com"]
  resources: ["evaluators", "models"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: evaluator-access-default
  namespace: default
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: evaluator-access-default
  apiGroup: rbac.authorization.k8s.io